// Export all garage components for easy importing
export { default as BasicCarInfo } from './BasicCarInfo';
export { default as CarImageManager } from './CarImageManager';
export { default as EngineDetails } from './EngineDetails';
export { default as WheelsAndTires } from './WheelsAndTires';
export { default as BrakingSystem } from './BrakingSystem';
export { default as SuspensionDetails } from './SuspensionDetails';
export { default as ExteriorMods } from './ExteriorMods';
export { default as InteriorMods } from './InteriorMods';
